server {
    listen 443 ssl http2;
    server_name ${DOMAIN_NAME};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/ssl/inception/fullchain.pem;
    ssl_certificate_key /etc/ssl/inception/privkey.pem;
    ssl_prefer_server_ciphers off;

    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # deny access to hidden files
    location ~ /\. {
        deny all;
    }
}
