services:
  # -------------------
  # MariaDB
  # -------------------
  mariadb	:
    container_name	: mariadb

    image			: mariadb

    build	:
      context		: ./requirements/mariadb
      dockerfile	: Dockerfile

    networks		:
      - inception-net

    volumes			:
      - db_data:/var/lib/mysql

    restart			: always

    env_file		: ./.env

  # -----------------------
  # WordPress
  # -----------------------
  wordpress	:
    container_name	: wordpress

    image			: wordpress

    build	:
      context		: ./requirements/wordpress
      dockerfile	: Dockerfile

    networks		:
      - inception-net

    volumes			:
      - wp_data:/var/www/html

    restart			: always

    env_file		: ./.env

    depends_on		:
      - mariadb

  # -------------------
  # NGINX
  # -------------------
  nginx		:
    container_name	: nginx

    image			: nginx

    build	:
      context		: ./requirements/nginx
      dockerfile	: Dockerfile

    networks		:
      - inception-net

    volumes			:
      - wp_data:/var/www/html

    restart			: always

    env_file		: ./.env

    depends_on		:
      - wordpress

    ports			:
      - "443:443"

# -------------------
# NETWORK
# -------------------
networks	:
  inception-net		:
    name			: inception-net

# -------------------
# VOLUMES
# -------------------
volumes		:
  db_data: # DB data
    driver		: local

    driver_opts	:
      o		: 'bind'
      type	: 'none'
      device: '/home/ytop/data/db_data'

  wp_data: # WP data
    driver		: local

    driver_opts	:
      o		: 'bind'
      type	: 'none'
      device: '/home/ytop/data/wp_data'
