[www]
user = nobody
group = nobody

; 'mariadb:9000' yerine '9000' portundan dinle.
; NGINX, bu konteynere 9000 portundan bağlanacak.
listen = 9000

; Dinamik süreç yönetimi
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Güvenlik için 'clear_env = no' ayarını kapatıyoruz ki
; .env dosyamızdaki değişkenleri PHP algılayabilsin.
clear_env = no